# Generated by Django 5.1.7 on 2025-04-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_song_lyrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='isPremium',
            field=models.BooleanField(default=False),
        ),
    ]
